models.py
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Column, Integer, String,Table,ForeignKey, DateTime
from sqlalchemy.orm import relationship

from datetime import datetime
import re

engine = create_engine('sqlite:///test.db', echo = True)

Base = declarative_base()

Session = sessionmaker(bind=engine)
session = Session()

post_tags = Table(
   'post_tags', Base.metadata,
   Column('tag_id', Integer, ForeignKey('posts.id')), 
   Column('post_id', Integer, ForeignKey('tags.id')) 
)

def slugify(string):
		pattern = r'[^\w+]'
		return re.sub(pattern, '-', string)

class Post(Base):
    __tablename__ = 'posts'

    id = Column(Integer, primary_key=True)
    slug = Column(String, unique=True)
    title = Column(String)
    body = Column(String)
    created = Column(DateTime, default=datetime.utcnow)
    tags = relationship("Tag",
                secondary=post_tags,
                backref="posts")

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.slug = slugify(self.title)

    def __repr__(self):
		    return f'<Post id {self.id} title: {self.title} slug: {self.slug} >'


class Tag(Base):
    __tablename__ = 'tags'

    id = Column(Integer, primary_key=True)
    slug = Column(String, unique=True)
    name = Column(String)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'Tag: {self.name}  slug: {self.slug} '



Base.metadata.create_all(engine)

posts/forms.py
from wtforms import TextField, TextAreaField, Form


class PostForm(Form):
    title = TextField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from models import Post, session, Tag
from posts.blueprint import posts

app = Flask(__name__)
app.register_blueprint(posts, url_prefix='/blog') 

app.config.from_pyfile('yourconfig.cfg')


###### Admin Panel ######
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

admin = Admin(app)
admin.add_view(ModelView(Tag, session))
admin.add_view(ModelView(Post, session))

main.py
from app import app
import view

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Post, Tag, session
from .forms import PostForm

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
def create_post():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            post = Post(title=title, body=body)
            session.add(post)
            session.commit()
        except:
            print('Error')
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/edit/<slug>', methods=['POST', 'GET'])
def edit_post(slug):
    post = session.query(Post).filter(Post.slug == slug).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        session.commit()

        return redirect(url_for('posts.detail', slug=post.slug))
    
    form = PostForm(obj=post)
    return render_template('posts/edit.html', form=form, post=post)

@posts.route('/')
def index():
    q = request.args.get('q')
    if q:
        all_post = session.query(Post).filter( Post.title.contains(q) | Post.body.contains(q) ).all()
    else:
        all_post = session.query(Post).all()
    return render_template('posts/index.html', all_post=all_post)


@posts.route('/<slug>')
def detail(slug):
    post = session.query(Post).filter(Post.slug == slug).first()
    return render_template('posts/detail.html', post=post)

@posts.route('/tag/<slug>')
def tag(slug):
    tag = session.query(Tag).filter(Tag.slug == slug).first()
    return render_template('posts/tag.html', tag=tag)

posts/templates/posts/create_post.html
{% extends 'base.html' %} {% block title %} Create Post {% endblock title %} {% block content_title
%}
<h3>New post</h3>
{% endblock content_title %} {% block content %}
<form class="col-md-6" action=" {{ url_for('posts.create_post') }} " method="POST">
  {% for input in form %}
  <div class="form-group">
    {{ input.label(class="control-label") }} {{ input(class="form-control") }}
  </div>
  {% endfor %}
  <br />
  <button type="submit" class="btn btn-primary">create</button>
</form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
<br />
{% block content %}
<h4>{{ post.title }}</h4>
<div>{{ post.body }}</div>

{% for tag in post.tags %}
<a class="btn btn-primary" href="{{ url_for('posts.tag', slug=tag.slug )}}" role="button">
  {{ tag.name }}
</a>
{% endfor %}
<br /><br />
<div>
  <a href="{{ url_for('posts.edit_post', slug=post.slug)}}" class="btn btn-success">Change</a>
</div>

{% endblock content %}

posts/templates/posts/edit.html
{% extends 'base.html' %} {% block title %} Create Post {% endblock title %} {% block content_title
%}
<h3>Edit post</h3>
{% endblock content_title %} {% block content %}
<form class="col-md-6" action=" {{ url_for('posts.edit_post', slug=post.slug) }} " method="POST">
  {% for input in form %}
  <div class="form-group">
    {{ input.label(class="control-label") }} {{ input(class="form-control") }}
  </div>
  {% endfor %}
  <br />
  <button type="submit" class="btn btn-primary">Change</button>
</form>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %} {% block title %} BluePrint {% endblock title %} {% block content_title %}
Post page {% endblock content_title %} {% block content %} {% for post in all_post %}
<li><a href="{{ url_for('posts.detail', slug=post.slug) }}"> {{ post.title }} </a></li>
{% endfor %} {% endblock content %}

posts/templates/posts/tag.html
{% extends 'base.html' %}
<br />
{% block content %}
<h3>Post for <span> "{{ tag.name }}" tag: </span></h3>

<ul>
  {% for post in tag.posts %}
  <li><a href="{{ url_for('posts.detail', slug=post.slug) }}"> {{post.title}} </a></li>
  {% endfor %}
</ul>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <title>{% block title %} {% endblock title %} Flask</title>
  </head>
  <body>
    <div class="container-fuild">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}"
                  >Blog</a
                >
              </li>
            </ul>

            <form class="d-flex" method="GET">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
                name="q"
                value="{{ request.args.get('q', '') }}"
              />
              <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      <div class="row">
        <h2>{% block content_title %} {% endblock content_title %}</h2>
        <div>{% block content %} {% endblock content %}</div>
      </div>
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %} {% block title %} Main Title {% endblock title %} {% block content_title%}
Main PAge {% endblock content_title %} {% block content %} Some Content {% endblock content %}